add google analytics event listeners
matas70/matas pull request #314
Opened 2022-03-15 14:50 UTC by bender2001

2022-03-15 14:53 UTC, bender2001 commented
wanted to say that added 3 event listeners with gtag

2022-03-17 19:03 UTC, NoamGaash commented
next time. please:
* edit the PR title
* add us as reviewers

2022-03-17 19:10 UTC, NoamGaash requested changes
הי מאיר
לא הצלחתי למצוא את השורות ששינית בקוד.
תוכל לפתוח branch חדש, ולשים שם רק קוד רלוונטי?
תודה
נעם

2022-03-17 19:10 UTC, NoamGaash commented on index.html
> +        console.log(window.dataLayer);
חבל להשאיר הערות בקוד
יהיה לנו הרבה ספאם בקונסול

2022-03-17 19:10 UTC, NoamGaash commented on js/HTMLMarker.js
> +  google.maps.event.addDomListener(
יש המון ריפקטורינג, זה מקשה על הבדיקה. צריך להתאמץ בשביל למצוא איפה הקוד שבאמת השתנה

2022-03-17 19:10 UTC, NoamGaash commented on js/date.js
> +Date.CultureInfo = {
😢

2022-03-22 12:17 UTC, closed without merging