add(some change in main.css (ar))
matas70/matas pull request #319
Opened 2022-04-03 14:00 UTC by AlisaZil

need to change old ar css to a new css

2022-04-04 13:33 UTC, NoamGaash commented
הי אליסה,
תוכלי לרשום קצת רקע מה הם השינויים, מי ביקש אותם, מתי ולמה?
למשל:
`style: make aircraft menu bigger`

2022-04-07 08:35 UTC, NoamGaash commented
אולי כדאי אפילו לצרף את הPDF של האפיון החדש לPR
שיהיה ברור מה הפיתוח שלך

2022-04-11 06:09 UTC, NoamGaash commented on ar.html
> +				<div>?שנתחיל עומר</div>
מה?

2022-04-11 12:52 UTC, AlisaZil commented on ar.html
> +				<div>?שנתחיל עומר</div>
שונה חזרה

2022-04-11 15:45 UTC, mayPeleg commented on js/functions.js
> +        arClick = false;
ההתייחסות פה היא רק לאייפון?

2022-04-11 15:49 UTC, mayPeleg commented on main.css
> +  width: 59px;
הגדלים החדשים הם לפי האיפיון?

2022-04-12 13:57 UTC, NoamGaash commented on js/AR.mjs
> +// <button id="ARButton" onclick='window.open("ar.html")'></button>
אולי עדיף למחוק את הקובץ וזהו?

2022-04-12 13:58 UTC, NoamGaash commented on js/functions.js
> +    // $("#aircraftInfoButton").click();b
b

2022-04-12 15:00 UTC, AlisaZil commented on main.css
> +  width: 59px;
כן

2022-04-12 15:06 UTC, NoamGaash commented on ar.html
> +				<p id="url-copied">הקישור הועתק! פרסם את זה עם חברים שלך</p>
מגניב

2022-04-12 15:07 UTC, NoamGaash commented on ar.html
> +					// if(showInfoPopup){
הרבה קוד בהערה
הוא רלוונטי?
אולי אפשר לוותר עליו

2022-04-12 15:09 UTC, NoamGaash requested changes
נראה שעשית עבודה טובה,
לא בדקתי אם זה עובד - סומך עליך שבדקת וראית שלא נשבר כלום.
אשמח אם תחזירי את package-lock למה שהיה קודם לפני שנמזג למאסטר

2022-04-12 15:56 UTC, AlisaZil commented on ar.html
> +					// if(showInfoPopup){
הקוד חשוב אני צריכה לתקן אותו קצת כשיהיה לי אנדרוייד לבדוק עליו
זה הפופ אפ הסבר על הar

2022-04-13 07:28 UTC, AlisaZil commented on js/functions.js
> +        arClick = false;
הוא בודק אם זה אייפון 
ואם לא הוא פשוט מעביר לעמוד בלי פונקציונליות

2022-04-13 07:41 UTC, NoamGaash commented on main.css
> +  display: none;
?

2022-04-13 07:43 UTC, AlisaZil commented on main.css
> +  display: none;
יש כפתור שיתוף למכשירים נתמכים ומכשירים לא נתמכים
זה נתמך לכן כשנכנסים למכשיר לא נתמך צריך להחביא אותו 
אני אשנה את השם כדי שיהיה מובן יותר.

2022-04-13 14:58 UTC, mayPeleg commented on js/functions.js
> +        arClick = false;
לעמוד ar בלי פונקציונליות נכון? לשנות את ה  -arClick  ל -false מבלבל קצת

2022-04-13 21:43 UTC, NoamGaash commented on ar.html
> +					// if(showInfoPopup){
בדרך כלל אנחנו לא תומכים בקוד בהערה, אבל מכיוון שיש לנו דד ליין קשיח שהקוד ייצא מהערה אני תומך בחריגה מהמדיניות הזו

2022-04-13 21:44 UTC, NoamGaash commented on main.css
> +  display: none;
הבנתי
זה יהיה `unsupported-share-button`?

2022-04-13 21:45 UTC, NoamGaash commented
שימי לב לקונפליקטים

2022-04-14 07:56 UTC, AlisaZil commented on main.css
> +  display: none;
 שונה

2022-04-14 07:57 UTC, AlisaZil commented on ar.html
> +					// if(showInfoPopup){
שיניתי וכרגע זה פועל

2022-04-14 07:58 UTC, AlisaZil commented on js/functions.js
> +        arClick = false;
אתקן בpr החדש מצאתי פונקציונליות יותר קלה שזה לבדוק אם ה chekbok בחור או לא

2022-04-14 08:19 UTC, NoamGaash commented on js/functions.js
> +        arClick = false;
סוכם בדיון - זה יבוצע בPR נפרד

2022-04-14 08:19 UTC, NoamGaash commented on js/functions.js
> +    // $("#aircraftInfoButton").click();b
```suggestion
    // $("#aircraftInfoButton").click(); 
```

2022-04-14 08:21 UTC, NoamGaash approved these changes

2022-04-14 08:25 UTC, merged

2022-04-16 08:14 UTC, NoamGaash commented
בין הפיתוחים השונים שנמצאים פה בPR בוצע פתרון של issue #325 לעמוד של הAR.