Add link
matas70/matas pull request #324
Opened 2022-04-13 07:49 UTC by bender2001

2022-04-13 14:52 UTC, mayPeleg commented on js/popups.js
>      baseArrivalExplanation: 'יש לחפש בוייז "בסיס רמת אביב" ואז לפנות שמאלה לנהריה שמה תהיה פניה לשער ירושלים',
במקום שיהיה הסבר כל כך ארוך.
מספיק לכתוב את ההסבר בקובץ  html ולשם למשוך את המיקום בוויז.
הדבר היחיד שמשתנה בין ההסברים של כל בסיס זה המיקום בוויז

2022-04-13 21:28 UTC, NoamGaash commented on js/popups.js
>      baseArrivalExplanation: 'יש לחפש בוייז "בסיס רמת אביב" ואז לפנות שמאלה לנהריה שמה תהיה פניה לשער ירושלים',
ההסברים לא אמורים להשתנות מבסיס לבסיס?

2022-04-14 07:52 UTC, bender2001 commented on js/popups.js
>      baseArrivalExplanation: 'יש לחפש בוייז "בסיס רמת אביב" ואז לפנות שמאלה לנהריה שמה תהיה פניה לשער ירושלים',
ההסברים הם דינמים אז אי אפשר לשנות אותו רק בHTML.
הם משתנים מבסיס לבסיס

2022-04-15 05:50 UTC, mayPeleg commented on js/popups.js
>      baseArrivalExplanation: 'יש לחפש בוייז "בסיס רמת אביב" ואז לפנות שמאלה לנהריה שמה תהיה פניה לשער ירושלים',
בטוח? לפי האיפיון הם לא משתנים מבסיס לבסיס, רק המיקום משתנה

2022-04-16 08:09 UTC, NoamGaash commented on js/popups.js
>      baseArrivalExplanation: 'יש לחפש בוייז "בסיס רמת אביב" ואז לפנות שמאלה לנהריה שמה תהיה פניה לשער ירושלים',
זה הסברים איך להגיע לבסיס,
נשמע לי הגיוני שלבסיסים שונים מגיעים בצורה שונה

2022-04-16 08:10 UTC, NoamGaash requested changes
* קונפליקטים
* תגובות

2022-04-17 06:52 UTC, bender2001 commented on js/popups.js
>      coronaIcon: 'randomIcon.svg',
תוקן

2022-04-18 19:27 UTC, mayPeleg commented
יש לך קונפליקטים.  תתקן על מנת שאוכל לעשות merge

2022-04-19 10:46 UTC, closed without merging