Voice messages
matas70/matas pull request #331
Opened 2022-04-14 11:33 UTC by mmuggia

Changed pop up closing from distance based to time based. added multiple recordings option. now a message will appear only if message from the same kind of aircraft wasn't sent already.

2022-04-14 12:01 UTC, NoamGaash commented on data/audio-messages.json
> +        "text": "שלום! כאן הצוות האווירובטי של חיל האוויר. אנו גאים לקיים את מטס ההצדעה לאזרחי ישראל, לרגל 73 שנים של עצמאות. חיל האוויר עומד מאחוריכם, ומאחל לכל עם ישראל בריאות איתנה, וחג עצמאות שמח
74 שנים

2022-04-14 12:05 UTC, NoamGaash commented on js/functions.js
> +                        let audioMessage = audioMessages[aircraft.aircraftTypeId] ? audioMessages[aircraft.aircraftTypeId] : audioMessages['default'];
אשמח אם תתייחס למקרה ש`audioMessages` הוא `unfinedined`

2022-04-15 06:01 UTC, mayPeleg commented on data/audio-messages.json
> +        "text": "שלום! כאן הצוות האווירובטי של חיל האוויר. אנו גאים לקיים את מטס ההצדעה לאזרחי ישראל, לרגל 73 שנים של עצמאות. חיל האוויר עומד מאחוריכם, ומאחל לכל עם ישראל בריאות איתנה, וחג עצמאות שמח
בכללי צריך להוסיף את הטקסטים שכבר יש לנו, אשלח גם בקבוצה

2022-04-15 06:02 UTC, mayPeleg commented on data/audio-messages.json
> +    "25": {
צריך להוסיף פה גם את השם של הפלטפורמה

2022-04-16 08:08 UTC, NoamGaash requested changes
עבודה מצויינת - בוא נתקן מה שנשאר ונמזג

2022-04-17 09:28 UTC, mmuggia commented on data/audio-messages.json
> +        "text": "שלום! כאן הצוות האווירובטי של חיל האוויר. אנו גאים לקיים את מטס ההצדעה לאזרחי ישראל, לרגל 73 שנים של עצמאות. חיל האוויר עומד מאחוריכם, ומאחל לכל עם ישראל בריאות איתנה, וחג עצמאות שמח
הוספתי את הטקסט, אני רק לא יודע באיזה מטוס טס המפעיל כטמ"ם

2022-04-18 10:58 UTC, NoamGaash approved these changes
נראה טוב

2022-04-18 10:59 UTC, merged