fix of supported AR
matas70/matas pull request #332
Opened 2022-04-14 13:38 UTC by AlisaZil

2022-04-14 14:04 UTC, NoamGaash requested changes
יכול להיות שעשית בטעות revert להרבה שינויים של מאיר?
תסתכלי על הPR שוב בבקשה

2022-04-14 14:04 UTC, NoamGaash commented on ar.html
> +					<button id="button-reset" class="support" alt="Draw" dis></button>
?

2022-04-14 14:04 UTC, NoamGaash commented on ar.html
> +				<button id="button-mode-toggle" alt="Toggle mode" class="dynamic" style="display: none;">
חשבתי שאנחנו לא אוהבים מצב דינאמי

2022-04-14 14:04 UTC, NoamGaash commented on ar.html
> +			let locations = []
למה?

2022-04-14 14:04 UTC, NoamGaash commented on ar.html
> -						gtag('event', 'ar_dynamic', {
למה

2022-04-15 06:19 UTC, mayPeleg commented on ar.html
> +				<button id="button-mode-toggle" alt="Toggle mode" class="dynamic" style="display: none;">
רצינו להשאיר רק את המצב הסטטי לא?
נראה שיש פה  חלק מהקוד שמאיר כתב

2022-04-15 06:22 UTC, mayPeleg commented
נראה שכשהורדת את ההחלפה בין מצב סטטי לדינאמי, עדיין נשאר ה - overlay שמסביר איך משתמשים ב - ar. שולחת גם תמונה

2022-04-18 08:17 UTC, NoamGaash commented on ar.html
> +				//navigator.clipboard.writeText("https://matas.iaf.org.il/ar.html צפו במטוסי חיל האוויר בתלת-מימד, באתר של מטס יום העצמאות!");
למה קוד בהערה?

2022-04-18 08:40 UTC, AlisaZil commented
> ,



> יכול להיות שעשית בטעות revert להרבה שינויים של מאיר? תסתכלי על הPR שוב בבקשה

2022-04-18 08:41 UTC, AlisaZil reviewed
.

2022-04-18 09:24 UTC, AlisaZil commented on ar.html
> -						gtag('event', 'ar_dynamic', {
שיניתי שהשינוי הבחירת 
שובל לא יהיה נראה

2022-04-18 09:24 UTC, AlisaZil commented on ar.html
> +				//navigator.clipboard.writeText("https://matas.iaf.org.il/ar.html צפו במטוסי חיל האוויר בתלת-מימד, באתר של מטס יום העצמאות!");
ייתכן שבטעות שמתי בהערה 
החזרתי

2022-04-18 09:25 UTC, AlisaZil commented
> יכול להיות שעשית בטעות revert להרבה שינויים של מאיר? תסתכלי על הPR שוב בבקשה

לא ראיתי שמחקתי שינויים שלו

2022-04-18 10:53 UTC, NoamGaash commented on ar.html
> +					<button id="button-reset" class="support" alt="Draw" dis></button>
לא מחקת.

2022-04-18 10:54 UTC, NoamGaash commented on ar.html
> +				<button id="button-mode-toggle" alt="Toggle mode" class="dynamic" style="display: none;">
לא שונה

2022-04-18 10:55 UTC, NoamGaash commented on ar.html
> -						gtag('event', 'ar_dynamic', {
זה לא קשור לבחירת שובל אלא לtoggle.
אם את כבר מעיפה, תעיפי הכל, לא רק את הgtag

2022-04-18 10:59 UTC, AlisaZil commented on ar.html
> -						gtag('event', 'ar_dynamic', {
אוקי העפתי

2022-04-18 11:00 UTC, AlisaZil commented on ar.html
> +				<button id="button-mode-toggle" alt="Toggle mode" class="dynamic" style="display: none;">
עכשיו שונה

2022-04-18 11:00 UTC, AlisaZil commented on ar.html
> +					<button id="button-reset" class="support" alt="Draw" dis></button>
גם כן נמחק

2022-04-18 11:05 UTC, NoamGaash commented on ar.html
> -						gtag('event', 'ar_dynamic', {
טרם

2022-04-18 11:06 UTC, NoamGaash commented on ar.html
> +			let locations = []
עדיין לא הבנתי מה ההבדל

2022-04-18 11:11 UTC, NoamGaash requested changes
מצויין לראות את ההתקדמות

2022-04-18 11:11 UTC, NoamGaash commented on ar.html
> +					//function eventFire(el, etype){
בכוונה קוד בהערה?

2022-04-18 11:11 UTC, NoamGaash commented on ar.html
> -					gtag("event", "ar_onPressReset", {
אם את מוחקת את כפתור reset, אפשר למחוק אותו כבר מכל מקום

2022-04-18 11:11 UTC, NoamGaash commented on ar.html
> +						locations = addMidpoints(locationsOptions[Math.floor(Math.random() * locationsOptions.length)], 20)
מחקת פה נקודה פסיק?

2022-04-18 11:11 UTC, NoamGaash commented on ar.html
> -						gtag('event', 'ar_dynamic', {
שמת בהערה, לא העפת

2022-04-18 11:11 UTC, NoamGaash commented on ar.html
> +					document.querySelector('#no-support-tutorial').style.display = 'none';
לשיקולך - אפשר ממש להעיף את כל אלה מהקוד.
לא חובה.

2022-04-18 12:20 UTC, AlisaZil commented on ar.html
> +					//function eventFire(el, etype){
כן

2022-04-18 14:37 UTC, AlisaZil commented on ar.html
> -					gtag("event", "ar_onPressReset", {
מחקתי

2022-04-18 14:38 UTC, AlisaZil commented on ar.html
> +						locations = addMidpoints(locationsOptions[Math.floor(Math.random() * locationsOptions.length)], 20)
יכול להיות 
מחקתי את הפונקציה

2022-04-18 16:53 UTC, AlisaZil commented on ar.html
> +						document.querySelector('.aircraft-option.selected').style.animation = `fillAnimation ${endTime}s`;
אוקי

2022-04-18 16:54 UTC, AlisaZil commented on ar.html
> +					document.querySelector('#no-support-tutorial').style.display = 'none';
העפתי

2022-04-18 16:55 UTC, AlisaZil commented on ar.html
> +			let locations = []
כשזה היה על 000 זה הראה מסלול התחלתי למרות שאין שום דבר 
אתחול של זה מנע מזה לקרות

2022-04-18 19:25 UTC, mayPeleg commented on main.css
> +} */
אין סיבה לשם בהערה. אפשר למחוק

2022-04-18 20:45 UTC, mayPeleg commented
מאושר!

2022-04-19 05:42 UTC, mayPeleg commented
תתקני את הקונפליקטים/ההערות בקבצים על מנת שאוכל לאשר את הpr:
ar.html
js/functions.js
main.css

2022-04-19 07:58 UTC, merged