fix bug of not showing menu in the matas navbar
matas70/matas pull request #346
Opened 2022-04-19 15:55 UTC by bender2001

2022-04-19 15:55 UTC, bender2001 commented
נעם ואליסה מבקש להתייחס

2022-04-20 05:15 UTC, mayPeleg commented on js/functions.js
> +let sortedLocations;
למה לא ב - var?

2022-04-20 05:18 UTC, mayPeleg commented on js/functions.js
> +    return !!locations.find(location => location && location.type === typeCategory);
אז למה צריך את sorterLOcation?  אין לו שימוש

2022-04-20 05:22 UTC, mayPeleg commented
מאושר. אליסה ונעם תעברו על זה גם לוודא שזה לא שובר כלום בAR

2022-04-20 05:31 UTC, mayPeleg commented on js/popups.js
> -]
בפונקציית showAircraftInfoPopup
קוראים למערך הזה ולפי השינוי שלך הוא קיים רק בתוך פונקציה אחת.

2022-04-20 08:07 UTC, bender2001 commented on js/functions.js
> +let sortedLocations;
אני ישנה

2022-04-20 08:18 UTC, bender2001 commented on js/functions.js
> +let sortedLocations;
בתיקון חדש שמתי בVAR

2022-04-20 10:56 UTC, NoamGaash requested changes

2022-04-20 10:56 UTC, NoamGaash commented on js/functions.js
> +var sortedLocations;
הוספת את המשתנה, איפה אתה משתמש בו?

2022-04-20 10:56 UTC, NoamGaash commented on js/popups.js
> +var aircraftUsdzObjData = [
למה לא const?

2022-04-20 10:56 UTC, NoamGaash commented on js/popups.js
> +    aircraftUsdzObjData = [
למה לא לשים את זה בdeclaration?

2022-04-20 10:56 UTC, NoamGaash commented on js/popups.js
> +    aircraftUsdzObjData = [
נראה כמו כפל קוד

2022-04-20 12:30 UTC, bender2001 commented on js/popups.js
> -]
אוקי

2022-04-20 12:32 UTC, bender2001 commented on js/popups.js
> +    aircraftUsdzObjData = [
איפה זה הdeclaration?

2022-04-20 12:37 UTC, bender2001 commented on js/functions.js
> +var sortedLocations;
הורדתי אותו.

2022-04-20 12:43 UTC, bender2001 commented on js/popups.js
> +    aircraftUsdzObjData = [
אם אני יוריד את הקוד אתה תראה שהבסיסים ,המיקומים והמטוסים נעלמים.
זה נראה כפילות אבל בגלל שהקוד לא הולך מלמעלה למטה אלה קופץ בין קבצים בתיקיית JS אז צריך להגדיר כמה פעמים את המערך מחדש כי הוא פשוט לא רואה אותו בפונקצייה.

2022-04-20 13:09 UTC, NoamGaash commented on js/functions.js
> +var sortedLocations;
ומה עם המשתנה locations?

2022-04-20 13:11 UTC, NoamGaash commented on js/popups.js
> +var aircraftUsdzObjData = [
לא הבנתי.
תסביר מתי אתה משתמש במשתנה, מתי אליסה משתמשת, מה הפונקציה שלך עושה, מה הפונקציה שלה עושה, לאיזו מטרה המערך הזה צריך להשתנות, מה לדעתך המערך מייצג כרגע ומה המערך צריך לייצג.

2022-04-20 13:13 UTC, NoamGaash commented on js/popups.js
> +    aircraftUsdzObjData = [
מה הוא רואה בפונקציה?
אם אתה בפונקציה ומנסה לעשות console.log למשתנה מה תראה?

2022-04-20 13:41 UTC, bender2001 commented on js/popups.js
> +    aircraftUsdzObjData = [
undefined

2022-04-20 13:45 UTC, bender2001 commented on js/popups.js
> +var aircraftUsdzObjData = [
הפונקצייה נקראת createTableRow.  אני משתמש בה כאשר יוצר בסיס בNavBar. לדעתי אין צורך בשינוי במערך אלה במיקום שלו ומומלץ להגיר אותו כמה פעמים בפונקציות שונות.

2022-04-20 15:59 UTC, mayPeleg commented
מאיר שים לב שיש לך קונפליקטים ולכן אי אפשר למרגג. יש שינויים שנעם ביקש שתעשה

2022-04-20 17:22 UTC, NoamGaash commented on js/popups.js
> +    aircraftUsdzObjData = [
מוזר,
אתה אומר את זה אחרי שבדקת והרצת?

2022-04-20 17:25 UTC, NoamGaash commented on js/functions.js
> +var sortedLocations;
כן אבל לא הצהרת עליו...

2022-04-20 22:48 UTC, merged