fix waze link inside popup
matas70/matas pull request #376
Opened 2022-04-25 06:57 UTC by bender2001

2022-04-26 13:00 UTC, mayPeleg commented
יש לך קונפליקטים. אני מנסה להבין גם למה עשית את זה?

2022-04-27 18:21 UTC, NoamGaash commented
אשמח גם להבין - יש כרגע באג? הוא פונה לשדה לא נכון?

2022-04-27 19:33 UTC, NoamGaash requested changes
conflicts + comments

2022-04-30 12:19 UTC, bender2001 commented
> mayPeleg

מתקן את הלינק של וייז בפופאפ.
משום מה הדרך הראשונה לא עובדת לי.

2022-04-30 12:25 UTC, closed without merging